from enum import Enum

from pydantic import BaseModel


class ErrorCode(str, Enum):
    PROVIDER_RATE_LIMITED = "PROVIDER_RATE_LIMITED"
    PROVIDER_TIMEOUT = "PROVIDER_TIMEOUT"
    PROVIDER_AUTH_FAILED = "PROVIDER_AUTH_FAILED"
    PROVIDER_BAD_SYMBOL = "PROVIDER_BAD_SYMBOL"
    PROVIDER_EMPTY_RESPONSE = "PROVIDER_EMPTY_RESPONSE"
    PROVIDER_UNSUPPORTED_ENDPOINT = "PROVIDER_UNSUPPORTED_ENDPOINT"
    PROVIDER_DATA_STALE = "PROVIDER_DATA_STALE"
    MARKET_DATA_UNAVAILABLE = "MARKET_DATA_UNAVAILABLE"
    UNAUTHORIZED = "UNAUTHORIZED"
    NOT_FOUND = "NOT_FOUND"
    VALIDATION_ERROR = "VALIDATION_ERROR"


class ErrorResponse(BaseModel):
    error_code: str
    message: str
    details: dict | None = None
